# Generated by Django 4.1 on 2022-08-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Violencia', models.CharField(choices=[('Domestica', 'Domestica'), ('Institucional', 'Institucional'), ('Laboral', 'Laboral'), ('Reproductiva', 'Reproductiva'), ('Mediatica', 'Mediatica'), ('Callejera', 'Callejera'), ('Obtetrica', 'Obtetrica')], default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Violencia', models.CharField(choices=[('Fisica', 'Fisica'), ('Psicologica', 'Psicologica'), ('Simbolica', 'Simbolica'), ('Sexual', 'Sexual'), ('Economica/patrimonial', 'Economica/patrimonial')], default=None, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Modalidad_de_violencia',
        ),
    ]
