# Generated by Django 4.1 on 2022-08-25 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo',
            old_name='Violencia',
            new_name='Violencias',
        ),
    ]
