# Generated by Django 4.1 on 2022-08-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
