# Generated by Django 4.1 on 2022-08-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_modalidad_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='caratula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Caratula', models.CharField(choices=[('Lesiones_leves', 'Lesiones_leves'), ('Lesiones_graves', 'Lesiones_graves'), ('Amenazas', 'Amenazas'), ('Abuso', 'Abuso')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='modalidad',
            name='Violencia',
            field=models.CharField(choices=[('Domestica', 'Domestica'), ('Institucional', 'Institucional'), ('Laboral', 'Laboral'), ('Reproductiva', 'Reproductiva'), ('Mediatica', 'Mediatica'), ('Callejera', 'Callejera'), ('Obtetrica', 'Obtetrica'), ('Fisica', 'Fisica'), ('Psicologica', 'Psicologica'), ('Simbolica', 'Simbolica'), ('Sexual', 'Sexual'), ('Economica/patrimonial', 'Economica/patrimonial')], max_length=100),
        ),
    ]
