# Generated by Django 4.1 on 2022-08-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_remove_victima_tipo_alter_agresor_dni_agresor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='Fecha_de_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='Año',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='Fecha_medida_plazo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='Fecha_recepcion',
            field=models.DateField(),
        ),
    ]
