# Generated by Django 4.1 on 2022-08-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_alter_caratula_id_alter_modalidad_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='victima',
            name='modalidad',
        ),
    ]
